apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - mariadb.yaml
  - wordpress.yaml
  - ingress.yaml
# Secret "wordpress-db" (root-password, password) lo crea Ansible en el servidor
